version: '3.9'

services:
  agent:
    build: .
    container_name: agent
    environment:
      PROMETHEUS_URL: 'http://victoriametrics:8428'
      LOG_FILE_PATH: '/var/log/agent.log'
    volumes:
      - ./data:/usr/src/app/data
      - ./logs/:/var/log/

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.78.1
    ports:
      - "8428:8428"
    volumes:
      - /storage
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=600'
    restart: always
